version: '3.7'
services:
  api:
    container_name: 'ebanx-api'
    build: '.'
    ports:
      - '8086:8086'
    depends_on:
      - 'mongo'
    environment:
      DB_URL_: "mongo-ebanx:27017"
      DB_NAME: "ebanx-bank"
      DB_USER: ""
      DB_PASS: ""
      DB_LOCAL: "Y"
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo-ebanx'
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./data:/data
    ports:
      - '27100:27017'